### ISSUE TITLE
시간표에 표시되는 시작 시간을 설정할 수 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by fhqlatm** [pdjdev/uTable#13]
### uTable\utable\Forms\Form1.vb

`
Dim min As Integer = 540
`

위 구문과 같이 수업 시간과 관계 없이 오전 9시로 설정하여 사용 중인데 

이와 관련하여 별도의 설정이 존재할까요 ?

**Comment by pdjdev** [comment]
좀 많이 늦었지만... 이번 업데이트에 반영하였습니다
피드백 감사합니다🫡
